### ISSUE TITLE
Support other DB engine

### ISSUE THREAD

**Issue by EvilLord666** [EvilLord666/ReportGenerator#1]
Test or maybe support (i don't know is it works with others DB engines or not):
-postgres
-mysql
-sqlite

**Comment by EvilLord666** [comment]
Sqlite works now, however i am planning to move common db code into separate Nuget package, therefore it will be easy to set up test infrastructure for not only this project

**Comment by stdstring** [comment]
mongo and other key-value DB (storages) ?

**Comment by EvilLord666** [comment]
Not in this task, possibly in other version of ReportGen 1.2 or above

**Comment by EvilLord666** [comment]
I've added support for MySql database (test 4 View works now) however there are 2 places where we have types specific for SqlServer

**Comment by EvilLord666** [comment]
ReportGenerator is also works with Postgres now

**Comment by EvilLord666** [comment]
However i faced problem with Postgres functions (i was unable to check and will solve this in #7 ) all code is ready we are able to extract data from sql server, mysql, sqlite and postgres
